# Generated by Django 3.1.2 on 2020-10-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='state',
            field=models.CharField(default='Rajasthan', max_length=50),
            preserve_default=False,
        ),
    ]
