# Generated by Django 3.1.2 on 2021-02-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0002_hospital_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientUser',
        ),
        migrations.RenameField(
            model_name='hospitaluser',
            old_name='has_opd_mgmt',
            new_name='has_opd_mgmt_acces',
        ),
        migrations.RemoveField(
            model_name='hospitaluser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='hospital',
            name='email_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='sms_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitaluser',
            name='opd_mgmt_access_type',
            field=models.CharField(default='r', max_length=2),
        ),
        migrations.AddField(
            model_name='hospitaluser',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hospitaluser',
            name='otp_time',
            field=models.DateTimeField(null=True),
        ),
    ]
