# Generated by Django 3.1.2 on 2021-02-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0003_auto_20210216_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitaluser',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='hospitaluser',
            name='last_name',
            field=models.CharField(default='na', max_length=50),
            preserve_default=False,
        ),
    ]
